# Generated by Django 3.2.4 on 2021-08-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_itinerary_productivity_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivity',
            name='activity_description',
            field=models.TextField(null=True),
        ),
    ]
