# Generated by Django 3.2.4 on 2021-08-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_productivity_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='activity_description',
            field=models.TextField(default=None),
        ),
    ]
