# Generated by Django 3.2.4 on 2021-08-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_productivity_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivity',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
