# Generated by Django 3.2.4 on 2021-08-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_productivity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('activityid', models.IntegerField()),
            ],
        ),
    ]
