# Generated by Django 3.2.4 on 2021-08-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='category',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
