# Generated by Django 3.2.4 on 2021-08-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_productivity_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='activityid',
            field=models.IntegerField(null=True),
        ),
    ]
